# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 981b973739beabe4426a9646003b162473e2817133270c75cd1dd2fb7daec1c3ea11d08040ba7ede5101ca4e706b4253325b837ffd69a4a7c5de4fc19932d508

test:
  secret_key_base: d8be2c74bf553936367d934995f8aa40d322a5defa8d9d26e0ab373612d141b3e5b7c0b53cba222b095d72c7ccafab24bff2866ae6350a21b3674e892f6f9b94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
